name: release

env:
  DOCKERHUB_REPO: "xjokay/ccu-historian"
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"
  VERSION: "latest"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "DATE=$(date -u +%Y-%m-%dT%H:%M:%S%z)" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes for release ${{ env.VERSION }} can be seen in the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ env.VERSION }}/CHANGELOG.md).
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            MAINTAINER=${{ github.repository_owner }}
            REPOSITORY=https://github.com/${{ github.repository }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
            DATE=${{ env.DATE }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
